#!/bin/bash
set -u -e -o pipefail

MOUNTS=200
ITERATIONS=100
PREFIX=$(pwd)/testdata/

# prepare
rm -rf $PREFIX
for d in $(seq $MOUNTS); do
	mkdir -p $PREFIX/$d
done

# test
for f in $(find $PREFIX -mindepth 1 -maxdepth 1 -type d); do
	./mnt-umnt $f $ITERATIONS &
done

wait

# cleanup
rm -rf $PREFIX || true
test -d $PREFIX && sudo umount -f $PREFIX/* || true
rm -rf $PREFIX
